In [1]:
import numpy as np

In [3]:
arr = np.array([10,20,30,40,50])
arr2 = np.array([1,2,3,4,5,"apna clg"])
print(arr,type(arr))
print(arr2,type(arr2))

[10 20 30 40 50] <class 'numpy.ndarray'>
['1' '2' '3' '4' '5' 'apna clg'] <class 'numpy.ndarray'>


In [19]:
# Using built-in Functions

arr = np.zeros((3,3))
print(arr,arr.shape,arr.size,arr.ndim)

arr2 = np.ones((2,3))
print(arr2,arr2.shape,arr2.size,arr2.ndim)

arr3 = np.arange(1,20,5)
print(arr3,arr3.shape)

arr4 = np.linspace(0,10,5)
print(arr4)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] (3, 3) 9 2
[[1. 1. 1.]
 [1. 1. 1.]] (2, 3) 6 2
[ 1  6 11 16] (4,)
[ 0.   2.5  5.   7.5 10. ]


In [24]:
# UsefulAttributes

arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr,arr.shape)
print(arr.size)
print(arr.ndim)
print(arr.dtype)
print(arr.itemsize)

[[1 2 3]
 [4 5 6]
 [7 8 9]] (3, 3)
9
2
int64
8


In [30]:
# Reshaping

arr = np.array([1,2,3,4,5,6])
print(arr)

reshaped = arr.reshape((2,3))
print(reshaped)

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


In [35]:
#  Indexing and Slicing

arr = np.array([10,20,30,40,50])
print(arr)
print(arr[0])
print(arr[1:5])
print(arr[2:])


[10 20 30 40 50]
10
[20 30 40 50]
[30 40 50]


In [47]:
# Aggregation Functions

arr = np.array([1,2,3,4,5,6])
print(arr)
print(np.sum(arr))
print(np.prod(arr))
print(np.min(arr))
print(np.max(arr))
print(np.argmin(arr))
print(np.argmax(arr))
print(np.mean(arr))
print(np.median(arr))
print(np.std(arr))
print(np.var(arr))
print(np.square(arr))
print(np.sqrt(arr))
print(np.pow(arr,3))

[1 2 3 4 5 6]
21
720
1
6
0
5
3.5
3.5
1.707825127659933
2.9166666666666665
[ 1  4  9 16 25 36]
[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  1   8  27  64 125 216]


In [50]:
# Broadcasting

arr = np.array([10,20,30,40,50])
print(arr+2)
print(arr**2)

arr1 = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,10])

print(arr1 + arr2)

[12 22 32 42 52]
[ 100  400  900 1600 2500]
[ 7  9 11 13 15]
